repos:
- repo: local
  hooks:
      - id: unittests
        name: run unit tests
        entry: python -m unittest
        language: system
        pass_filenames: false
        args: ["discover"]
      - id: ruff # Linter
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: ruff check --force-exclude
        language: system
        require_serial: true
        types_or: [ python, pyi ]
        args: [ --fix]
        stages: [commit, manual]