name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      COMET_WORKSPACE: ${{ secrets.COMET_WORKSPACE }}
      COMET_MODEL_NAME: ${{ secrets.COMET_MODEL_NAME }}
      COMET_PROJECT_NAME: ${{ secrets.COMET_PROJECT_NAME }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy model
      run: |
        python models/deploy.py
