name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call_setup_and_install:
    uses: ./.github/workflows/setup_and_install.yml


  call_run_tests:
    needs: call_setup_and_install
    uses: ./.github/workflows/run_tests.yml

  call_train:
    needs: call_run_tests
    uses: ./.github/workflows/train.yml

  call_deploy:
    needs: call_train
    uses: ./.github/workflows/deploy.yml
