name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call_setup:
    uses: ./.github/workflows/setup.yml

  call_install_dependencies:
    needs: call_setup
    uses: ./.github/workflows/install_dependencies.yml

  call_run_tests:
    needs: call_install_dependencies
    uses: ./.github/workflows/run_tests.yml

  call_deploy:
    needs: call_run_tests
    uses: ./.github/workflows/deploy.yml
