name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call_run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

  call_train:
    needs: call_run_tests
    uses: ./.github/workflows/train.yml
    secrets: inherit

  call_deploy:
    needs: call_train
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
